services:
  turtlebot3-arm64:
    platform: "linux/arm64"
    build:
      platforms:
        - "linux/arm64"
      context: ./
      dockerfile: ./docker/Dockerfile
      args:
        ROS_DISTRO: jazzy
  turtlebot3-x64:
    platform: linux/amd64
    build:
      platforms:
        - "linux/amd64"
      context: ./
      dockerfile: ./docker/Dockerfile
      args:
        ROS_DISTRO: jazzy
